apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsync
  labels:
    app: cloudsync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudsync
  template:
    metadata:
      labels:
        app: cloudsync
    spec:
      containers:
        - name: cloudsync
          image: 27malisha/cloudsync-app:552fc73
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi